### ISSUE TITLE
Decarb 23 - Initial Changes to website

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#1]
Hi @osamajandali 

Thanks for your time earlier

### What needs to be visible: 

- [x] ~Coming in November 2023 (underneath 'The latest advancements in Green Software')~
- [x] Add date **16th November 2023**
- [x] Add dynamic time **2pm GMT/UTC**
- [x] "Sign up for Info" email form + button
- [x] About Section (Adam will provide new copy below) - leaving the Register CTA close the top
- [x] Restore the footer with GSF logo
- [x] Logos of all the SC members under heading "GSF Steering Committee"
- [x] Button under SC logos to "Full list of members" (pointing at https://greensoftware.foundation/)

### 
What needs to be hidden

- [x] Next Steps
- [x] Agenda
- [x] Video
- [x] Navigation floating bar, hide for now

### UI Changes

- [x] Change copyright date to 2023
- [x] Change 'register' button to 'Notify when registration opens'
- [x] Website uses American spelling (for consistency we need to use the logo with the 'z' rather than the 's'
- [x] Add CTA button at the bottom of the page to jump to reg form section
![Decarbonize Software_logo_vertical_for dark bg](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/c6be5f63-3bd8-4d91-bef2-5c589651a500)

**Comment by zanete** [comment]
@adamj89 FYI have added to @osamajandali board :)

**Comment by osamajandali** [comment]
@adamj89 It's live now.
Remove the footer for now, no need for a footer in coming soon page.

**Comment by adamj89** [comment]
Here is the initial copy for the about section:

### **About the event**

Decarbonize Software is an annual event by the Green Software Foundation showcasing the advancements in Green Software by the community. After an incredible 2022 event where we announced the Software Carbon Intensity Specification, our new Linux Foundation training program and our catalogue of Green Software Patterns - we're handing much of the 2023 event to our community to see what you built with the portfolio of tools from the GSF. We're also excited to share what we've been up to at the Foundation.

Our 2023 event will take place on 16th November 2023. 

### **Speaking at Decarbonize Software**

Our community Call for Papers will be opening soon. We're looking for 10-12 minute lightning talk or demo sessions covering the following:

- Showing how you used or built upon Open-Source tooling from the GSF
- How you've built a Green Software community in your organisation
- Talking in-depth about an insight from the State of Green Software report
- Showcase the best of your local or regional community group
- Telling us what you've learned as a GSF Member (GSF member orgs only)

### **About the GSF**

The Green Software Foundation is a non-profit organisation and part of the Linux Foundation. Our mission is to build a trusted ecosystem of people, standards, tooling and best practices for creating and building green software. Head over to greensoftware.foundation to find out more about our working groups and projects.

**Comment by adamj89** [comment]
@osamajandali about text is above and have added the following asks (updated in issue)
- add SC logos
- link to other members
- add in date/time
- change text on registration button
- restore footer

**Comment by zanete** [comment]
Capturing the status in the weekly call:
- this is the highest priority as we want to push this live asap

**Comment by osamajandali** [comment]
It's done @adamj89 
https://decarb.greensoftware.foundation/
Just couple of things here:
- We need to have a CTA for the call for papers section
- 'Notify when registration opens' as a button text is too long I used 'Notify me'

**Comment by adamj89** [comment]
Thanks so much @osamajandali 

Final thing I think. The preview when posting in slack comes through like this: 

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/9f4cf4b0-79c0-4697-9f39-20c8515d7885)

- [ ] Can we change that preview text? 
It should read
> Green Software Foundation is excited to host an event in November to highlight advancements in decarbonizing software.

- [ ] And the card needs updating to say November 16th 2pm GMT | 9am ET

Thank you so much!

**Comment by osamajandali** [comment]
@adamj89 sure I am gonna update those.

Did we agree on having a CTA on the call for papers section? if yes, where it should point to ?

**Comment by zanete** [comment]
- [ ] The CTA "Submit a session" underneath the "Speaking at Decarbonize Software" bullet points
- [ ] grnsft.org/decarb/speakers

**Comment by adamj89** [comment]
@NAMRATA-WOKE has asked if we can include another button just above the footer saying 'Register now' 

The register now button would jump to the form section. 
 
Is this possible?

**Comment by osamajandali** [comment]
All updates are done @adamj89

**Comment by adamj89** [comment]
Thanks @osamajandali , closing this as complete
