### ISSUE TITLE
[Recreated issue] Copy updates for Decarb

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#10]
Copying issue over from https://github.com/Green-Software-Foundation/gsf-admin/issues/292 as private issues can't be transferred.

What: The Decarbonize Software Landing Page to build interest and a bank of subscribers to boost registration needs more text.
Why: This is the Foundation's flagship event to celebrate progress made, recognize opportunities for improved collaboration, partnership, transparency and tooling, and announce new resources to advance the practice of green software.
How: The webcopy for the landing page will be informational, inspiring and evoke a sense of possibility.

@NAMRATA-WOKE 

@osamajandali the below section replaces the section which stars with "Combat Climate change using green software principles and best practices"

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/0fc52c2e-edbc-4f9c-9bb0-b652c225b88a)

---

**Decarbonize Software 2023
Redefining the future of software**

Decarbonize Software takes place on 16th November 2023. This digital event is your all-access pass to see the impressive strides taken in making software more environmentally friendly and climate-conscious. It's an open invitation for both seasoned sustainability advocates and those new to the cause, all poised to make a real impact as climate champions in tech. Decarbonize Software is open to all and features the voices of our community, as well as the latest updates from the Green Software Foundation.

**Unveiling Our Vision**

With COP28 kicking off on 30th November in Dubai, we wanted to highlight projects which are driving momentum towards a low-emission and climate-resilient world. At COP28, global leaders will discuss how to reduce global Green House Gas emissions by 43% by 2030. In sync with this ambitious goal, Decarbonize Software is our platform to position software at the forefront of climate action.

On 16th November, the Green Software Foundation will bring software practitioners across the globe together to highlight big wins and to see what's possible in the future. This event will also mark the launch of new tools and resources by the Foundation to support individual contributors across industry and academia, propelling an even more significant reduction in software's carbon footprint.

**Reserve Your Spot**

Sign up now to receive notifications about the event, our call-for-speakers and more. Decarbonize Software is a digital (online) event. There is no cost to attend, and the event is open to all. [View our Code of Conduct](https://greensoftware.foundation/code-of-conduct).

**Comment by adamj89** [comment]
@osamajandali, @NAMRATA-WOKE has requested this copy change. Let's discuss in the meeting.

**Comment by osamajandali** [comment]
Updated!
