### ISSUE TITLE
Typo correction - "Sell full list" > "See full list"

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#11]
Hi @osamajandali 

Picked up a small typo on the site (well Chris Skipper did - I didn't spot it!). 

The button below Steering members says "Sell full list" instead of "See full list". Can we correct this? 
![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/25063c93-7ba3-421e-adb9-759a3548939e)

**Comment by osamajandali** [comment]
Updated!
