### ISSUE TITLE
GS Practitioners Course Pre-Registration Engagement Campaign for Decarb 2023

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/decarbonize-software-event#12]
What: Linear sequenced emails to GSF  to encourage them to register for Decarb 2023
Why: The email campaign is designed to motivate software practitioners to register for Decarbonize Software on November 16 and progressively engage and educate them. The campaign is designed to ensure potential attendees are informed about the topics, their relevance to the impact they want to have in their career and jobs, and are aware of the pace of change possible with their continued support.
How: Practitioners enrolled in the GS Practitioners course will receive the email campaign via LF Hubspot. 

[Link to emails](https://docs.google.com/document/d/1VpL5M4EmTMX7DdJQJT1gxtOnFVlm8DaOcPpsyLgxAUU/edit?usp=sharing)

# Resources

* Hubspot campaign: https://app.hubspot.com/marketing/8112310/campaigns/8174f223-128d-4dae-ab2d-d15cd0cd55e5/assets
* Email 1: https://app.hubspot.com/email/8112310/edit/133255738478/content

# Actions

- [x] Create Hubspot campaign
- [x] Create email 1
- [x] Create email 2
- [x] Create email 3
- [x] Create email 4
- [x] Create email 5
- [x] Create email 6
- [x] Create email 7 
- [x] Create email 8 
- [x] Decide whether we need to change the footer details
- [x] Decide if we want to send from our own domain or not
- [x] Setup new google group to use as FROM address (learn@)
- [x] Schedule email 1
- [x] Schedule email 2
- [x] Schedule email 3
- [x] Schedule email 4
- [x] Schedule email 5
- [x] Schedule email 6
- [ ] Schedule email 7
- [ ] Schedule email 8
- [ ] LF to get the contact list updated with all the recent enrolments (Missing 3k)
- [ ] Resend email 1 to those who didn't open

**Comment by NAMRATA-WOKE** [comment]
### Header for all emails 
![Image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/114516498/e8c654c2-8c11-46ac-b8bd-f4bc4ba2e80b)


### Image for GSF Discussions
![Image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/114516498/9827f714-16ac-48ff-ae77-6c4e3e279e51)

**Comment by russelltrow** [comment]
@NAMRATA-WOKE who should the email come from? You?

**Comment by NAMRATA-WOKE** [comment]
It's always more effective when coming from an individual. Is it possible to come from you? Are you comfortable with that? 

From individuals, it should read "Namrata from the GSF" or "Russell from the GSF"

Alternatively, it should go out from the GSF and read "Green Software Foundation" the email: help@greensoftware.foundation.

**Comment by russelltrow** [comment]
I'm happy for it to come from me in name and then use the help@ email incase we have a flood of replies. Can we all access that email?

Also because we don't have our domain connected to HubSpot it will show "via hubspot" in the FROM 

"The email sending domain (greensoftware.foundation) isn't connected to your account. This will cause the recipients' inbox provider to add ‘via HubSpot’ to your From address."

**Comment by russelltrow** [comment]
All emails have been created in Hubspot: https://app.hubspot.com/email/8112310/manage/folder/128893884951

**Comment by russelltrow** [comment]
One other issue we that LF's hubspot doesn't appear to be fully synced with their LMS so we are missing a couple of thousand learners who have recently enrolled.

https://app.hubspot.com/contacts/8112310/lists/8384/filters

I've raised this with LF, hopefully I'll get a response ASAP

**Comment by NAMRATA-WOKE** [comment]
@russelltrow thanks for the update. Strange there's a discrepancy here. From my understanding, this was all automated. Do we have to refresh the list they built for us?

**Comment by NAMRATA-WOKE** [comment]
@russelltrow waiting on LF to see if we can get the full list of people enrolled. Giving them until the end of this week. If not, still moving ahead and will schedule the campaigns to go live starting next Tuesday at 6:30 IST.

**Comment by russelltrow** [comment]
The first email is scheduled to send on Tuesday 12th September at 18:30 IST ([everytime](https://everytimezone.com/?t=64fe5880,8ac))

Preview: https://email.linuxfoundation.org/join-green-software-mvps-at-decarbonize-software-2023?hs_preview=NJzmKZCr-133255738478

**Comment by NAMRATA-WOKE** [comment]
@seanmcilroy29 would really love to send this campaign out starting Tuesday of next week, so if we can place some urgency on this issue, that would be great. Happy to help and liaise with @russelltrow if required. 

We're not sending any stand-a-lone communication to our 5K subscribers on Mailchimp because we made the decision to prioritize this large audience and use Decarb as an opportunity to engage him for the first time.

**Comment by seanmcilroy29** [comment]
@NAMRATA-WOKE - @russelltrow already has access to HubSpot to send out a campaign with the GSF subscription list

**Comment by russelltrow** [comment]
All working now, thanks so much @seanmcilroy29

**Comment by russelltrow** [comment]
The campaign has been sent!

* [Hubspot campaign report](https://app.hubspot.com/email/8112310/details/133255738478/performance)
* [Decarb webpage analytics](https://analytics.google.com/analytics/web/?authuser=2#/p338674891/realtime/overview)
