### ISSUE TITLE
Decarbonize Software Run of Show

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#13]
ALL TIMES IN UTC/GMT

| Time  | Topic | Speakers | Notes |
| ------------- | ------------- | ------------- | ------------- |
| 1400  | **Introduction**  | @adamj89 @NAMRATA-WOKE  |   |
| 1403  | **2023 in Review**  | @jawache (Opt: @russelltrow) |   |
| 1409  | 🎥 **Member Video 1**  | Member name |   |
| 1410  | _Driving Climate Change Solutions with AI_ | Charlotte Degot, CEO and Co-Founder of CO2 AI & Diana Dimitrova, Managing Director and Partner at BCG | This session delves into the imperative need for AI and digital solutions to execute measurement and reduction strategies at scale. You will discover insights on the benefits of utilizing technology as a cornerstone for accurately measuring and effectively reducing carbon emissions and share practical examples to accelerate progress towards a more sustainable future. Join us as we explore how organizations can revolutionize sustainability practices and foster a greener, more responsible world. |
| 1424  | 🎥 **Member Video 2**  | Member name |   |
| 1425  | _Engineering Excellence with GSF Principles & Patterns_ | Chris Howard, Open Source Program Office Lead, EPAM | Join for a fast-paced introduction into how EPAM are leveraging GSF's principles and patterns coupled with the engineering know-how of 50,000+ engineers to build greener, sustainable and better software for our clients. We'll share how we've ran-up a working group of our leading engineers, architects and others to build new approaches that help our clients with their sustainability targets, cost savings and of course carbon emission reductions. |
| 1439  | 🎥 **Member Video 3**  | Member name |   
| 1440  | **Responsible AI: Fireside Chat** | Jesse Mccrosky, Head of Sustainability and Social Change and Principal Data Scientist at Thoughtworks | This fireside chat explores the ethical and environmental implications of artificial intelligence. Jesse Mccrosky will share insights on how to design, develop, and deploy AI solutions that are aligned with the principles of green software and social good. |
| 1459  | 🎥**Member Video 4**  | Member name |   
| 1500  | _High-quality energy data for emission optimizations_ | Johann Hemmann, Yvette Nartey & Jonathan Noormann, CODE University | Join the team of three from CODE University in Berlin as they present their project, working title "Emission meter 🔋". The goal of the project is to enable developers to measure energy consumption of the full application stack as easily as any other metric. This data then can be used to optimize the energy consumption of clients and backend services, as well as to calculate the SCI score. Johann, Yvette and Jonathan are working on this as their final project for their studies. |
| 1514  | 🎥**Member Video 5**  | Member name |   
| 1515  | **GSF Champions** | Adam Jackson, Namrata Narayan | Programme Launch |
| 1525  | **~GSF Experts~** | ~Asim Hussain~ | ~Announcement of initial 5 experts~ |
| 1534  | 🎥**Member Video 6**  | Member name |   
| 1535  | _Towards a Sustainable Software Engineering Framework_ | Angel Doru Cataron & Stefanie Wolf | In this presentation, Angel & Stefanie introduce their Sustainable Software Engineering Framework, which defines seven essential topic clusters supporting software engineering teams in the reduction of energy consumption at Siemens. Topic clusters include sustainability measurement and models - as well as architecture patterns and practices. For each of these topic clusters in the framework, they started with collecting and creating adequate methods, concepts, architectures, and building blocks that are included or referenced by the Sustainable Software Engineering Framework.  |
| 1550  | --- BUFFER TIME --- | --- | --- |
| 1559  | 🎥**Member Video 7**  | Member name |   
| 1600  | [**IEF Demo** ](https://github.com/Green-Software-Foundation/decarbonize-software-event/issues/14)| @jawache + @navveenb  | Notes |
| 1624  | 🎥**Member Video 8**  | Member name |   
| 1625  | _Emissions Impossible: From home insights to a greener workplace_ | Dan Benitah & Vaughan Knight | The Carbon Aware SDK helps you understand the emissions in the grid that powers your software, which in turn can help you design and build better software by making greener decisions.  In this session the team from the CA SDK will demonstrate how they are using the CA SDK in their day-to-day lives to reduce their household emissions, and how this has become a way for them to drive green software culture in their companies.  |
| 1639  | 🎥**Member Video 9**  | Member name |   
| 1640  | **Closing** | GSF Staff | --- |
| 1645  | **Off Air** | --- | --- |

**Comment by adamj89** [comment]
Great feedback! Thank you. We'll go ahead with the fireside chat.
Who is the host?

**Comment by NAMRATA-WOKE** [comment]
@adamj89 what's filling in for GSF Experts?

**Comment by mattc-fixitinprod** [comment]
@adamj89, I have a few holes in the Talent tab in our RoS/[production doc](https://docs.google.com/spreadsheets/d/1vN_cgZaJx6XzNmh1fMQidqPkXWR1Ml1QpYWb-wCrdwA/). Emails for everyone would be helpful if I need to ping them for their presentation decks, currently missing address for Charlotte and Jesse. Sofie I don't have any info for and need her full name, title and company affiliation to be able to create her Lower Third/Namekey. Perhaps @NAMRATA-WOKE has some of these details too.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design why do you want to remove Tammy?

Dan and Vaughan already have their titles in there.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE I couldn't see Tammy is the table above and in the [airtable](https://airtable.com/app9St20Uuado5ufM/tblaepGxS9TPTAGKP/viwErlFASSm4VEdmX?blocks=hide) 
 though she was in [your canva file](https://www.canva.com/design/DAFyK8gaWq8/Z7764G9AAKPWWyhOT1AnkQ/edit?ui=eyJEIjp7IkEiOnsiQSI6IktBRnlNWU9lZnR3In19fQ) that was my first source 2 weeks ago
For Dan and Vaughan I've added 'Software Engineer' for each as a placeholder, I didn't find their tittles in the tables, but I can see that somebody added the companies
Please let me know if you need me to apply any adjustments
