### ISSUE TITLE
Update Copy on Decarb (Speakers Section)

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#15]
Hi @osamajandali could you do a quick update for me today?

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/d4305781-beed-41b6-82cc-3eef232abb7b)

Change this line:

~Our community Call for Papers will be opening soon~
_to_
**Our call for speakers is now open!**

**Comment by osamajandali** [comment]
@adamj89 Done!

**Comment by adamj89** [comment]
Thank you!
