### ISSUE TITLE
Script for Decarb for Environment Variables

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/decarbonize-software-event#18]
What: Draft a script for Chris Skipper to promote Decarb 2023 
Why: Environment Variables is our fastest growing content marketing channel with over 100,000 downloads. 
How: Google doc

**Comment by NAMRATA-WOKE** [comment]
Hey there, podcast listeners! Get ready for something big!

Join us on November 16 for "Decarbonize Software" by the Green Software Foundation. 

It's your all-access pass to the future of tech and climate action! COP28 is coming, and we're putting software at the forefront of climate action. 

Open to all, this event unveils new tools and resources to cut software's carbon footprint.

It's free to attend! Register now at grnsft.org/decarb and be a part of the change.

**Comment by sonicfutures** [comment]
Hey @NAMRATA-WOKE this is great! Can I just suggest a change to the first line to something more casual like:

**Hey Everyone, Asim here with a big announcement!**

**Comment by jawache** [comment]
Hey @sonicfutures and @NAMRATA-WOKE recorded it here: https://riverside.fm/studio/decarb-announce
