### ISSUE TITLE
Decarb Agenda for Website

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#20]
ALL TIMES IN UTC/GMT

| Time  | Topic | Speakers | 
| ------------- | ------------- | ------------- | 
| 1400  | **Introduction and 2023 in Review**  | Adam Jackson, Namrata Narayan & Asim Hussain - Green Software Foundation  |  
| 1410  | _Driving Climate Change Solutions with AI_ | Charlotte Degot, CEO and Co-Founder of CO2 AI & Diana Dimitrova, Managing Director and Partner at BCG |
| 1425  | _Engineering Excellence with GSF Principles & Patterns_ | Chris Howard, Open Source Program Office Lead, EPAM |
| 1440  | **Responsible AI: Fireside Chat** | Jesse Mccrosky, Head of Sustainability and Social Change and Principal Data Scientist at Thoughtworks | 
| 1500  | _High-quality energy data for emission optimizations_ | Johann Hemmann, Yvette Nartey & Jonathan Noormann, CODE University | 
| 1515  | **Our new GSF Champions** | Adam Jackson, Namrata Narayan - Green Software Foundation | 
| 1535  | _Towards a Sustainable Software Engineering Framework_ | Angel Doru Cataron & Stefanie Wolf - Siemens | 
| 1600  | **Introducing the Impact Framework** | Asim Hussain - Chair & Executive Director at Green Software Foundation
| 1625  | _Emissions Impossible: From home insights to a greener workplace_ | Dan Benitah & Vaughan Knight - Avanade |
| 1640  | **Closing Remarks** | GSF Team |

**Comment by adamj89** [comment]
@osamajandali hi! Could you please add this to the Decarb website as soon as you're able to.
Cc @NAMRATA-WOKE

**Comment by osamajandali** [comment]
Done!
