### ISSUE TITLE
Changes to Published Agenda to show new speakers

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#28]
@osamajandali please can I request the following change to the Decarb agenda:

###  16:00 | Introducing the Impact Framework |

`In addition to Asim please add: `
- **Navveen Balani | Chief Technologist, Technology Sustainability Innovation at Accenture**
- **Srinivasan Rakhunathan | Senior Program Manager at Microsoft**

**Comment by osamajandali** [comment]
Done!
