### ISSUE TITLE
Upload of presentation decks

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#30]

**Comment by mattc-fixitinprod** [comment]
@adamj89, I've created a [Dropbox File Request link](https://www.dropbox.com/request/WXtDLl10hHXbkQjDkmho) that can be shared with any presenters needing to get their presentation assets to us. I have also included a field in the Tech Check Calendly questionnaire for people to provide download links if they are hosting them elsewhere. As files are shared, I will update this thread and our [production doc](https://docs.google.com/spreadsheets/d/1vN_cgZaJx6XzNmh1fMQidqPkXWR1Ml1QpYWb-wCrdwA/<https://docs.google.com/spreadsheets/d/1vN_cgZaJx6XzNmh1fMQidqPkXWR1Ml1QpYWb-wCrdwA/).
