### ISSUE TITLE
Add videos to the Decarb Ageda

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/decarbonize-software-event#31]
- [ ] @adamj89  to add the videos
- [ ] @osamajandali  to propose how the visual
- [ ] @adamj89  to implement

14:00 | Introduction and 2023 in Review | Adam Jackson, Namrata Narayan & Asim Hussain, Green Software Foundation
-- | -- | --
**followed by a message from Toru Shimogaki - NTT Data**
14:10 | Driving Climate Change Solutions with AI | Charlotte Degot & Diana DimitrovaCEO and Co-Founder of CO2 AI & Managing Director and Partner at BCG
**followed by a message from Navveen Balani - Accenture**
14:25 | Engineering Excellence with GSF Principles & Patterns | Chris HowardOpen Source Program Office Lead, EPAM
**followed by a message from Matthew Kropp - BCG X**
14:40 | Responsible AI: Fireside Chat | Jesse MccroskyHead of Sustainability and Social Change and Principal Data Scientist at Thoughtworks
**followed by a message from Marco Valtas - Thoughtworks**
15:00 | High-quality energy data for emission optimizations | Johann Hemmann, Yvette Nartey & Clara Janke, CODE University
15:15 | Our new GSF Champions | Adam Jackson, Namrata NarayanGreen Software Foundation
15:35 | Towards a Sustainable Software Engineering Framework | Angel Doru Cataron & Stefanie WolfSiemens
**followed by a message from Thomas Lewis - Microsoft**
16:00 | Introducing the Impact Framework | Asim HussainChair & Executive Director at Green Software Foundation
**followed by a message from Geetha Gandhi - Avanade**
16:25 | Emissions Impossible: From home insights to a greener workplace | Dan Benitah & Vaughan KnightAvanade
16:40 | Closing Remarks | GSF Team

**Comment by adamj89** [comment]
Added video references in as a line under each relevant session

@osamajandali please note the third speaker for the CODE University session is now Clara Janke - delete Jonathan

**Comment by osamajandali** [comment]
@adamj89 sorry I can't understand, where is the videos exactly? is it a text only or what I didn't get it sorry

**Comment by osamajandali** [comment]
Added the following line under the agenda as discussed in slack
```
Throughout the event, short messages from our Steering members including NTT Data, Accenture, BCG, Thoughtworks, Microsoft & Avanade.
```
