### ISSUE TITLE
URGENT: Live Event YouTube Player

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#36]
On the 16th November, a few hours before the event, we need to embed this YouTube video in the website and take the registration form offline:

https://www.youtube.com/watch?v=fGFeHaYtf5A

@osamajandali can this be scheduled?

**Comment by osamajandali** [comment]
@adamj89 Yes, please tell me the exact time that you this to be live on website

**Comment by zanete** [comment]
The event starts at 14:00 UTC (so the player should be showing from 13:00 UTC)

**Comment by osamajandali** [comment]
It's live now
