### ISSUE TITLE
Add Tammy to Decarb Agenda

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/decarbonize-software-event#37]
@osamajandali can you please add Tammy to the Decarb agenda? 

14:40 
Responsible AI: Fireside Chat 

Jesse McCrosky, Head of Responsible Tech and Principal Data Scientist at Thoughtworks
Tammy McClellan, Sr. Cloud Solution Architect at Microsoft + Co Chair, Community WG and OC at GSF

Thank you!

**Comment by NAMRATA-WOKE** [comment]
FYI @adamj89

**Comment by osamajandali** [comment]
Done

**Comment by adamj89** [comment]
Thanks!
