### ISSUE TITLE
Nurture Campaign for Decarb 2023

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#4]
The email journey for decarb is not working. When someone submits a form on the site it goes into this journey from 2022

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/ff2b6dc6-0fb3-4623-b01a-7544a21615db)

This needs to be resolved before we can start talking about the event.

**Comment by NAMRATA-WOKE** [comment]
@adamj89 @russelltrow **[Review the updated email campaign](https://docs.google.com/document/d/1nKuKjFV9PhygnCVvSuTpd02vVuxZJhB8fPGwQi_bI08/edit?usp=sharing)** for post-registration. Let me know what you think and feel free to be candid about what you'd like changed.
