### ISSUE TITLE
Post-Event Decarb website changes

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#40]
Hi @osamajandali 

Please could you action the following:

- [x] Change website 'description' to `Decarbonize Software | Watch on-demand`

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/e91151fb-5166-4dda-8df6-b0981e96616c)

- [x] Change text in paragraph 1 to _"Decarbonize Software `took` place on 16th November 2023"_

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/e6828ddb-0343-4e68-a6c6-bdabbddf35f5)

- [x] Change text in paragraph 3 to the following
_"On 16th November, the Green Software Foundation `brought` software practitioners across the globe together to highlight big wins and to see what's possible in the future. This event `also marked` the launch of new tools and resources by the Foundation to support individual contributors across industry and academia, propelling an even more significant reduction in software's carbon footprint. `You can now watch the event on-demand through the video player above`"_
![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/170119e8-b578-45de-a9b8-7f26f1be82d7)

- [x] Remove paragraph 4
![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/a55eea39-d0ef-4c03-9a73-018e946369f3)

- [x] Change CTA on button to _"`Watch on-demand`"_

![image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/20337337/0b0d8818-f4c0-42f9-bf36-959b82896a28)

- [x] Remove all timings in agenda block, but leave session names and speakers

Thank you :)

**Comment by osamajandali** [comment]
Done!

**Comment by zanete** [comment]
Reviewed and happy with changes! fyi @adamj89
