### ISSUE TITLE
Edited videos for each session

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#41]
Create edits for each of the following content blocks as standalone videos @mattc-fixitinprod, with top & tail and mistakes edited out as best possible. Might also want to edit out if possible the bit where the presenter mentions the previous SC video/coming SC video. SoW amendment needed for this work item.

- [x] Driving Climate Change Solutions with AI
- [x] Engineering Excellence with GSF Principles & Patterns
- [x] Responsible AI: Fireside Chat
- [x] High-quality energy data for emission optimizations
- [x] Towards a Sustainable Software Engineering Framework
- [x] Introducing the Impact Framework
- [x] Emissions Impossible: From home insights to a greener workplace

@adamj89 to ping @seanmcilroy29 about SoW extension possibility

**Comment by mattc-fixitinprod** [comment]
@adamj89, posting to acknowledge this task. I will get an SoW over to @seanmcilroy29 asap.

**Comment by adamj89** [comment]
FYI @NAMRATA-WOKE

**Comment by mattc-fixitinprod** [comment]
@adamj89 @NAMRATA-WOKE

Here is the [link](https://www.dropbox.com/scl/fo/8vma9d9nefgkjblnxpoop/h?rlkey=y0arv6hfz9vre7thcc231rsap&dl=0) to the folder with individual videos and the individual links below:

- [Driving Climate Change Solutions with AI](https://www.dropbox.com/scl/fi/02zcswshdl1kbsq3jpi4n/GSF-Decarb-2023-Driving-Climate-Change-Solutions-with-AI.mp4?rlkey=qflr3hat0utbrduv2iav1m6k6&dl=0)
- [Engineering Excellence with GSF Principles & Patterns](https://www.dropbox.com/scl/fi/2a3z9npi610rtzhmawki5/GSF-Decarb-2023-Engineering-Excellence-with-GSF-Principles-Patterns.mp4?rlkey=4niidnmy23o90zenh268e03cd&dl=0)
- [Responsible AI: Fireside Chat](https://www.dropbox.com/scl/fi/4950ok9ftlpu2rrbz8yzw/GSF-Decarb-2023-Responsible-AI-Fireside-Chat.mp4?rlkey=exiwmfuwp1datsqekoi7f9ec1&dl=0)
- [High-quality energy data for emission optimizations](https://www.dropbox.com/scl/fi/2x3fvtttmns470u78rdfx/GSF-Decarb-2023-High-quality-Energy-Data-for-Emission-Optimizations.mp4?rlkey=vb74wj5eqocg9a4sa73nb36ht&dl=0)
- [Towards a Sustainable Software Engineering Framework](https://www.dropbox.com/scl/fi/x2v5ednsrudxfih147lel/GSF-Decarb-2023-Towards-a-Sustainable-Software-Engineering-Framework.mp4?rlkey=0hkusdfxj0yo4en1ptsy2iwdg&dl=0)
- [Introducing the Impact Framework](https://www.dropbox.com/scl/fi/t029xp275071wrlsfgvp1/GSF-Decarb-2023-Introducing-the-Impact-Framework.mp4?rlkey=5me0zzskkep2y401hwdu2sd2e&dl=0)
- [Emissions Impossible: From home insights to a greener workplace](https://www.dropbox.com/scl/fi/cwz0evjt1srulo6c3nv4l/GSF-Decarb-2023-Emissions-Impossible-From-Home-Insights-to-a-Greener-Workplace.mp4?rlkey=wadzputp0hlwqjuqygymfcccr&dl=0)

Let me know if you'd like to setup a call to chat about any changes!

**Comment by mattc-fixitinprod** [comment]
Hey @adamj89 and @NAMRATA-WOKE, just making sure you saw these were submitted last week. I am going to go ahead and send the invoice to @seanmcilroy29, but please feel free to send me any notes if you like any of the segments adjusted.
