### ISSUE TITLE
Set up reg form on Decarb website

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#6]
#### _Deadline to have this live in time for launch on 5th September_

**Why**: Starting full registration from the get-go and need more information about each participant into the mailchimp audience
**Scope of work**:
- [x] create a new mailchimp form https://github.com/Green-Software-Foundation/decarbonize-software-event/issues/4 
- [x] replace existing form with additional fields: Name, Email, Role, Country
- [x] Mandatory fields are: **Name, Email**
- [x] Make country as a dropdown
- [x] Keep the "Also subscribe to GSF newsletter"  
- [x] Replace the CTA to say "Register"
- [x] Tag the subscriber as subscribing for "Decarb 2023" so that 
- [x] On Submission, the "Register" button becomes "Add to Calendar" button and go with link **grnsft.org/decarb/calendar-2023** (@NAMRATA-WOKE  can also use this link as the Add to Calendar link in the registration confirmation email)
- [x] Communicate the Add to calendar ACTUAL link to @zanete for short-link setup
- [x] Share on social button _LinkedIn_ and _X_

**Comment by adamj89** [comment]
Request from @NAMRATA-WOKE to add in LinkedIn/Twitter sharing button upon successful registration. 

This would consist of a social graphic "I'm registered for Decarbonize Software" and some text which @NAMRATA-WOKE will provide.
@osamajandali is this possible? This can come after the reg form is done as it is further down the priority order.

**Comment by NAMRATA-WOKE** [comment]
**LinkedIn text for social sharing:**

I'm attending Decarbonize Software on November 16. If you're interested in reducing software's environmental footprint and the open-source projects by the Green Software Foundation, join me ➡️ https://decarb.greensoftware.foundation/

**Twitter text for social sharing:**

Join me at Decarbonize Software on Nov 16! Let's reduce software's environmental impact together. RSVP ➡️ https://decarb.greensoftware.foundation/

**Comment by osamajandali** [comment]
- The website form is updated and it is linked to mailchimp with tag "Decarb 2023"
- The link to calendar is https://decarb.greensoftware.foundation/decarb-2023.ics
- @NAMRATA-WOKE Linkedin sharing only allow links sharing, I can't associate a text with it
cc: @adamj89

**Comment by NAMRATA-WOKE** [comment]
@adamj89 is there a shortlink you want to share for the decarb website (assuming it's the destination for the livesteam)?

**Comment by adamj89** [comment]
https://grnsft.org/decarb

**Comment by osamajandali** [comment]
Hey @NAMRATA-WOKE, 
It seems okay to me but I am not expert in marketing neither in creating users journeys. So it's better to contact a marketeer in this matter. I can only help in anything related to the form integration in the website.

**Comment by adamj89** [comment]
OK, it seems pretty urgent that we activate it since people are now accessing the site. Appreciate anything you can do to get this switched on.

Best wishes,
Adam Jackson
Program Manager - Green Software Foundation
Community Working Group

**Comment by osamajandali** [comment]
@adamj89 Yes I can activate it if this is the case

**Comment by NAMRATA-WOKE** [comment]
@osamajandali yes please activate!

**Comment by NAMRATA-WOKE** [comment]
@osamajandali can you confirm what audience people who register on the website go into in Mailchimp? Since the decarb audience is empty, it might be better for them to go into the general one if we can tag them at the time of registering "decarb 2023".
