### ISSUE TITLE
Create 90 second video per SC member

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#7]
We will create a video with each Steering Committee Member. 60 seconds ideally, 90 seconds max per video.

Each would be asked a question & introduce their organisation. The video will be shown at Decarbonize Software. 

Target Date: 30th October 2023

Description: Pre-recorded videos from each Steering Committee member of around 60 seconds answering a predetermined question about Decarbonizing Software. This is important to showcase the leadership and expertise of the GSF and to provide insights and perspectives on the event’s theme and objectives.

Definition of Done (DoD): Nine videos are received from the Steering Committee members, each lasting for around 60 seconds. 

KPI: 

The number of videos received divided by the number of Steering Committee members. The target is 9 out of 11 (82%). 

The number of views, likes, comments, and shares generated by the videos. The target is at least 1,000.

**Comment by NAMRATA-WOKE** [comment]
@adamj89 how were you thinking about communicating this ask? I can connect with all the marketing/comms folks next week with the ask & guidelines, in addition to informing them about the CFP.

**Comment by adamj89** [comment]
Here are some possible questions for the Green Software Foundation Steering Members:

- What are your main goals as a GSF steering member?
- How do you define green software?
- What are the benefits of adopting green software principles and practices?
- What are some of the challenges or barriers that you face in implementing green software?
- What are some of the projects or initiatives that you are currently working on with the GSF?
- Which tools or methods do you use to measure the carbon impact of your software?
- What are some of the best practices or tips that you can share with other software developers or organizations who want to reduce their carbon footprint and create more sustainable software?
- How do you collaborate with other GSF members & communities?
- How do you balance the trade-offs between performance, functionality, user experience, and environmental impact when designing or developing software applications?
- How do you communicate or educate your staff about the importance and value of green software?
- Which trends & innovations are you are looking forward to in the field of green software?

**Comment by adamj89** [comment]
Production Requirements for SC members:

- [ ] Put forward a senior employee involved with the GSF and /or Org Sustainability leadership. 
- [ ] Set aside 15-30 minutes (hopefully 15, 30 just in case of tech setup changes) to record video
- [ ] Video has 2 parts: Introduction to Organisation, how long they have been involved with the GSF (30 seconds)
- [ ] Answer a question from the list above, or craft their own question with us (45 seconds)
- [ ] Producer will edit the video.

**Comment by adamj89** [comment]
### Memo to SC Members:

The Green Software Foundation (GSF) is organizing a decarbonize software event in 2023, and we invite you to participate and showcase your leadership and commitment to green software. As a steering committee member, you have the opportunity to share your insights and experiences with the global software community and inspire others to join the green software movement.

To participate, we ask you to put forward a senior employee who is involved with the GSF and/or your organization’s sustainability leadership. They will be asked to record a short video (90 seconds max) that will be featured on the event website and social media channels. The video will consist of two parts: a brief introduction of your organization and its involvement with the GSF (30 seconds), and an answer to one of the questions from the list below (45 seconds). The questions are designed to highlight your achievements, challenges, best practices, and vision for green software.

The questions are:

What are your main goals as a GSF steering member?
How do you define green software?
What are the benefits of adopting green software principles and practices?
What are some of the challenges or barriers that you face in implementing green software?
What are some of the projects or initiatives that you are currently working on with the GSF?
Which tools or methods do you use to measure the carbon impact of your software?
What are some of the best practices or tips that you can share with other software developers or organizations who want to reduce their carbon footprint and create more sustainable software?
How do you collaborate with other GSF members & communities?
How do you balance the trade-offs between performance, functionality, user experience, and environmental impact when designing or developing software applications?
How do you communicate or educate your staff about the importance and value of green software?
Which trends & innovations are you are looking forward to in the field of green software?
You can choose one of these questions or craft your own question with us. We will provide you with the technical guidance and support for recording and editing the video. We hope that you will join us in this exciting event and help us spread the word about green software.

Please let us know if you have any questions or feedback.

**Comment by NAMRATA-WOKE** [comment]
BCG X - Matthew Kropp
Thoughtworks - Lisa McNally

**Comment by mattc-fixitinprod** [comment]
> Do we know how we're scheduling slots for the recordings?

Hey Namrata,

We haven't been introduced quite yet, but I saw the question and have an answer. I will be setting up a Calendly today so you will have a link to share with them. They'll be able to schedule blocks of my time for their recording sessions. I have a few days I have to blackout, but otherwise I will keep it very open for them as I'm sure we have some international participants in different timezones. I am in Seattle, WA (Pacific Time) for reference.

**Comment by NAMRATA-WOKE** [comment]
@mattc-fixitinprod can you share your email address with me on Slack or via email to namrata@greensoftware.foundation?

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

So far, we have two scheduled through Calendly. I will repost this list with additional speakers as they schedule with me and I will strike out those that have completed their sessions.

1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA - 06:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture - 11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Two more added to the list, one of which is tomorrow. Little concerned that our target nine have not booked time or reached out. Do you have updates from anyone on their end?

1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
06:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture 
11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

3. Matt Kropp, Managing Director & Senior Partner, BCG

**Comment by NAMRATA-WOKE** [comment]
@mattc-fixitinprod I'll follow-up with GitHub, UBS and Avanade again. I just spoke with Thomas from Microsoft so his booking should come in soon.

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Updating the list, no new entries but some news regardless. Toru cancelled their session stating that they will record it themselves and send me the camera file. Matt and Marco have been recorded and will be edited this week!

~~1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
6:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture 
11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

~~3. Matt Kropp, Managing Director & Senior Partner, BCG
1:30pm - Friday, October 20, 2023 (Pacific Time - US & Canada)~~

~~4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
7:00am - Monday, October 23, 2023 (Pacific Time - US & Canada)~~

**Comment by NAMRATA-WOKE** [comment]
@mattc-fixitinprod did Thomas Lewis schedule time with you?

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Yes, looks like he booked yesterday for this Friday. Here is the updated list:

~~1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
6:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture 
11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)

~~3. Matt Kropp, Managing Director & Senior Partner, BCG
1:30pm - Friday, October 20, 2023 (Pacific Time - US & Canada)~~

~~4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
7:00am - Monday, October 23, 2023 (Pacific Time - US & Canada)~~

5. Thomas Lewis, Principal Green Software Advocate, Microsoft
01:30pm - Friday, October 27, 2023 (Pacific Time - US & Canada)

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Just got a notice in my inbox that Sanjay Podder has rescheduled tonights session to Friday morning. Here is the updated list:

~~1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
6:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture 
~~11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~
6:00am - Friday, October 27, 2023 (Pacific Time - US & Canada)

~~3. Matt Kropp, Managing Director & Senior Partner, BCG
1:30pm - Friday, October 20, 2023 (Pacific Time - US & Canada)~~

~~4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
7:00am - Monday, October 23, 2023 (Pacific Time - US & Canada)~~

5. Thomas Lewis, Principal Green Software Advocate, Microsoft
01:30pm - Friday, October 27, 2023 (Pacific Time - US & Canada)

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE, I intend to have all of the edits in version 1 by EoD 10/27 with voices cleaned up, music beds added and graphics added for the presenters names, but do you have any graphics assets you want added for the beginning or end of each video? At least for the social post versions? For the live versions, we will want a clean head and tail to be inserted into the show, so I'll be exporting a two versions each.

**Comment by NAMRATA-WOKE** [comment]
@mattc-fixitinprod Has Ben Logan from UBS scheduled time? 

GitHub is no longer doing it. 

@adamj89 we've officially announced Siemens as a new SC. Can we extend this opportunity to them and give them GitHub's slot?

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE, I have not seen anything from Ben Logan yet. I am okay with extending availability, I know we were wanting more of these done and honestly they will help the live show flow better. I will adjust Calendly to add what time I can for the next week.

#@adamj89, no worries for the change in scope (no need for a change order) if you're okay with some of these late videos not being finished in time for social posts. We will for sure have the five on time videos ready for social by Monday mornin per original scope, but I do need to know if there needs to be any graphic added to them like an informational slide with a RSVP link or something of the like. Currently, they fade in from black with some instrumental driving music, their name and title pops on screen and then we fade out to black at the end. I feel it could use some ending call to action slide.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you support and create some intro/outro cards?

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE @mattc-fixitinprod 

Please check if I understand the task correctly
- intro card: Decarbonizing Software logo + Nov 16 date
- outro card: Decarbonizing Software logo + registration link 
- size: HD 1920x1080, 1200x1200 for social   
- file format: do you prefer vector?

Do you need a separate frame for each speaker with their name, title and additional design elements?
If yes, is this a complete list?
1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture
3. Matt Kropp, Managing Director & Senior Partner, BCG
4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
5. Thomas Lewis, Principal Green Software Advocate, Microsoft

Thank you

**Comment by adamj89** [comment]
@Jenya-design the cards should not have the Nov 16th date on them. It can just be a general Decarbonize Software gfx.

**Comment by adamj89** [comment]
@mattc-fixitinprod happy for recordings to slip a few days. We should set a deadline for end of next week if poss

**Comment by adamj89** [comment]
@NAMRATA-WOKE good to go on Siemens as long as they can do by EONW

**Comment by mattc-fixitinprod** [comment]
@adamj89, sounds good, I have updated my Calendly with next week availability.

@Jenya-design, thanks for hopping on that. Wanted to clarify, is the separate frame you mentioned for name and title a full screen graphic or a lower third? @adamj89, might want you to throw your opinion in here.

Last year we used [these](https://www.dropbox.com/scl/fo/9nlouv6ogxsl1zmgcer4t/h?rlkey=5024u6ygkef2b1n1bfwu1skg4&dl=0) that are a bit simple, happy to update or incorporate what Jenya can come up with.

An example of how they simply faded on and off is seen [here](https://www.dropbox.com/scl/fi/aof4lmoavpuhetkl95on2/GSF-Lightning-Talk-Gaida-Zirkelbach-V2.mp4?rlkey=opxqoqtqcwl3pltcw7mchynyo&dl=0) and if you scrub through a little further, you can see the look that we used for the live show with the person next to their slides.

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Sanjay Podder had a conflict, so Navven Balani filled in. Regardless, recording complete! Here is the updated list:

~~1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
6:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~

2. Sanjay Podder, Managing Director & Global Lead for Technology Sustainability Innovation, Accenture
~~11:00pm - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~
6:00am - Friday, October 27, 2023 (Pacific Time - US & Canada)

~~3. Matt Kropp, Managing Director & Senior Partner, BCG
1:30pm - Friday, October 20, 2023 (Pacific Time - US & Canada)~~

~~4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
7:00am - Monday, October 23, 2023 (Pacific Time - US & Canada)~~

5. Thomas Lewis, Principal Green Software Advocate, Microsoft
01:30pm - Friday, October 27, 2023 (Pacific Time - US & Canada)

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

Sanjay Podder had a conflict, so Navven Balani filled in. Regardless, recording complete! Here is the updated list:

~~1. Toru Shimogaki, Head of Green Innovation Office, NTT DATA
6:00am - Wednesday, October 25, 2023 (Pacific Time - US & Canada)~~

~~2. Navven Balani, Chief Technologist - Technology Sustainability Innovation, Accenture
6:00am - Friday, October 27, 2023 (Pacific Time - US & Canada)~~

~~3. Matt Kropp, Managing Director & Senior Partner, BCG
1:30pm - Friday, October 20, 2023 (Pacific Time - US & Canada)~~

~~4. Marco Valtas, Technical Lead for Cleantech and Sustainability NA, Thoughtworks
7:00am - Monday, October 23, 2023 (Pacific Time - US & Canada)~~

5. Thomas Lewis, Principal Green Software Advocate, Microsoft
01:30pm - Friday, October 27, 2023 (Pacific Time - US & Canada)

One more to go today and then waiting on additional SC members to schedule their sessions for next week.

**Comment by Jenya-design** [comment]
@mattc-fixitinprod @adamj89 @NAMRATA-WOKE 
Please check pdf preview attached, there are:
intro card: Decarbonizing Software logo 
outro card: Decarbonizing Software logo + registration link
size: HD 1920x1080, 1200x1200 for social
lower thirds (I've put a grey bg to make white elements visible, png on Drive are transparent)

[ai vector files and png with transparency here](https://drive.google.com/drive/folders/1bp7A2h0H5odnlts3qGhPDESjIIxM-_Rt?usp=drive_link)

@mattc-fixitinprod I can add separate frame for name and title if you think it'll work better with the structure of the video than lower third. Let me know if you need any adjustments or additional elements
Thank you

[01_Decarbonize Software_video assets.pdf](https://github.com/Green-Software-Foundation/decarbonize-software-event/files/13190192/01_Decarbonize.Software_video.assets.pdf)

**Comment by mattc-fixitinprod** [comment]
@Jenya-design, I tried to request access to the Google Drive link but got a weird error I've not seen before. Could you add permissions for mattc@fixitinprod.com? The PDF loaded fine, those graphics look fantastic! Do you mind if I add a little animation to the lower thirds?

**Comment by Jenya-design** [comment]
Sorry @mattc-fixitinprod, I'm not sure what's the issue, it should be the public drive
It looks like I don't have the permission to add you there
Please try the attachment or [this links ](https://drive.google.com/drive/folders/1Wkquv_7BrLNKxrF726FRNQgMksWUz-qQ?usp=sharing)
Yes please, animated lower third would be perfect, thank you so much!
Let me know if you need anything else

[01_Decarbonize Software_video assets.zip](https://github.com/Green-Software-Foundation/decarbonize-software-event/files/13191577/01_Decarbonize.Software_video.assets.zip)

**Comment by mattc-fixitinprod** [comment]
@Jenya-design, can you share the font you used?

**Comment by mattc-fixitinprod** [comment]
@Jenya-design, @adamj89, @NAMRATA-WOKE

How do we feel about this?

https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/116089665/ba4709de-91cd-4881-8458-e643f894bb49

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE

The five that we had previously scheduled are all complete. You'll find the Live versions and the Social versions [here](https://www.dropbox.com/sh/83jxkascgb2g9ou/AAAiezYtTIs_91UwXBZ2hCT0a?dl=0). The Live versions do not have the slates so that we can transition to them cleanly during the stream. In one instance, Matt Kropp finished his recording with a call to action to watch the stream so I edited that out of the Live version.

I have not seen any new scheduled sessions, but it's still the weekend so I'm sure we'll see some tomorrow.

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE and @adamj89

I wanted to get ahead of lower thirds for the live stream, could you two review this list and make any corrections you see needed? Some of the names I could not find a title for.

- Adam JacksonCommunity Lead | Green Software Foundation
- Namrata Narayan Director of Communications & Member Relations | Green Software Foundation
- Asim Hussain Executive Director | Green Software Foundation
- Charlotte Degot CEO and Co-Founder | CO2 AI
- Diana Dimitrova Managing Director and Partner | BCG
- Chris Howard Open Source Program Office Lead | EPAM
- Jesse Mccrosky  Head of Sustainability & Social Change and Principal Data Scientist | Thoughtworks
- Johann Hemmann Student | CODE University
- Yvette Nartey Student | CODE University
- Jonathan Noormann Student | CODE University
- Angel Doru Cataron UNKNOWN
- Stefanie Wolf UNKNOWN
- Dan Benitah UNKNOWN
- Vaughan Knight UNKNOWN

**Comment by mattc-fixitinprod** [comment]
@adamj89 @NAMRATA-WOKE, I've invited you two as editors of my Google Sheet Run of Show and accompanying info doc. Please feel free to continue using GitHub, but know that this is the document that my crew and I will be referencing throughout the live stream.

This [link](https://docs.google.com/spreadsheets/d/1vN_cgZaJx6XzNmh1fMQidqPkXWR1Ml1QpYWb-wCrdwA/edit?usp=sharing) can be used to view without signing into Google.

**Comment by NAMRATA-WOKE** [comment]
@mattc-fixitinprod 

Angel Doru Cataron, Researcher at Siemens 
Stefanie Wolf Software Engineer at Siemens 
Dan Benitah, Solutions Architect at Avanade 
Vaughan Knight, Principal Engineering Manager at Microsoft

**Comment by Jenya-design** [comment]
@mattc-fixitinprod I can see you request for the fonts and lower third animation review in my email notifications
I it's still relevant,  think animation is perfect. The font is Nunito (Bold and Regular) unfortunately I can't access the font files right away and share with you as I'm using it via adobe subscription
I think it'll be faster if you go ahead and add all the confirmed speakers, but let me know if you need my help with this - I'll assist asap
Thank you

**Comment by mattc-fixitinprod** [comment]
@NAMRATA-WOKE, are we sharing final edits with the presenters? I know GSF has its own promotion posts strategy, but BCG is asking for their video to do their own. I can send it right away if you green light it.

**Comment by adamj89** [comment]
Approved from my side.

**Comment by adamj89** [comment]
@mattc-fixitinprod could you email the videos over to me as well (for social). Can't find the link!

**Comment by mattc-fixitinprod** [comment]
> @mattc-fixitinprod could you email the videos over to me as well (for social). Can't find the link!

Sent!

**Comment by NAMRATA-WOKE** [comment]
Shared the video with all interviewees. Will move start date for socializing the videos to next week to give them a day or two to share any concerns. Will move forward if we receive no responses. @mattc-fixitinprod you're cc'd on all emails for visibility and to take any quick actions. 

Avanade and UBS are pending, correct?

**Comment by mattc-fixitinprod** [comment]
Thank you @NAMRATA-WOKE, I'll keep an eye out for any notes from the Steering Members. So far, looks like they're all happy.

> Avanade and UBS are pending, correct?
I have Avanade scheduled Nov. 6th 9:30am Pacific. I haven't seen a booking for UBS yet.

**Comment by mattc-fixitinprod** [comment]
Our sixth and last SCM video is [here](https://www.dropbox.com/scl/fi/t4cwc61g2lpz8rz9qvdyf/GSF_231116_Decarb23_SCM_GeethaGanghi_Social.mp4?rlkey=ejc54h5fe9vpg0bx3vidvab1q&dl=0) from Geetha Gandhi of Avanade.

**Comment by adamj89** [comment]
Thanks @mattc-fixitinprod
