### ISSUE TITLE
Social "join me" graphic for Decarb

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/decarbonize-software-event#8]
@Jenya-design please can we request a social graphic for Decarb

It would consist of 

-Green Software Foundation graphic- 
"Join me at Decarbonize Software"
"November 16th"
"grnsft.org/decarb"

Deadline is 4th September. 

Fine to adapt existing illustrations if needed

**Comment by Jenya-design** [comment]
@adamj89 please review the options attached or [in Canva](https://www.canva.com/design/DAFtfSCzFVU/6U936Ce-xJ8FYasCSNn2IQ/edit?utm_content=DAFtfSCzFVU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)


![Image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/69306070/5040fa0c-edb9-476f-8ef6-2d91d0e2fce7)


![Image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/69306070/819e0315-2838-4d67-b83a-d134ebfbece8)


![Image](https://github.com/Green-Software-Foundation/decarbonize-software-event/assets/69306070/ebee8a7f-e49e-441a-a7d2-54b8111236fc)

**Comment by adamj89** [comment]
Love these. Thanks so much!
